ALTER SESSION
SET
  "_ORACLE_SCRIPT" = true;

CREATE USER zerobased identified BY zerobased;

GRANT ALL PRIVILEGES TO zerobased;

CONNECT zerobased / zerobased @ORCLCDB;

DROP SEQUENCE permission_seq;

DROP SEQUENCE interest_seq;

DROP SEQUENCE vote_seq;

COMMIT;

DROP TABLE TopicChange CASCADE CONSTRAINTS;

DROP TABLE EditRequest CASCADE CONSTRAINTS;

DROP TABLE UserInterest CASCADE CONSTRAINTS;

DROP TABLE UserBadge CASCADE CONSTRAINTS;

DROP TABLE Vote CASCADE CONSTRAINTS;

DROP TABLE Badge CASCADE CONSTRAINTS;

DROP TABLE Interest CASCADE CONSTRAINTS;

DROP TABLE Permission CASCADE CONSTRAINTS;

DROP TABLE Topic CASCADE CONSTRAINTS;

DROP TABLE TopicTag CASCADE CONSTRAINTS;

DROP TABLE UserAccount CASCADE CONSTRAINTS;

CREATE TABLE Permission (
  Id NUMBER(38) NOT NULL PRIMARY KEY,
  Name VARCHAR2(50) NOT NULL,
  Description VARCHAR2(50)
);

CREATE TABLE Badge (
  Name VARCHAR2(50) NOT NULL PRIMARY KEY,
  Points NUMBER(38) NOT NULL,
  PermissionId NUMBER(38) REFERENCES Permission(Id)
);

CREATE TABLE UserAccount (
  Username VARCHAR2(50) NOT NULL PRIMARY KEY,
  FirstName VARCHAR2(50),
  LastName VARCHAR2(50),
  Password VARCHAR2(50),
  JoinDate DATE DEFAULT SYSDATE,
  Points NUMBER DEFAULT 0,
  Email VARCHAR2(50)
);

CREATE TABLE UserBadge (
  Username VARCHAR2(50) NOT NULL REFERENCES UserAccount(Username),
  BadgeName VARCHAR2(50) NOT NULL REFERENCES Badge(Name),
  PRIMARY KEY (Username, BadgeName)
);

CREATE TABLE Interest (
  Id NUMBER(38) NOT NULL PRIMARY KEY,
  Name VARCHAR2(50)
);

CREATE TABLE Topic (
  Name VARCHAR2(50) NOT NULL PRIMARY KEY,
  FilePath VARCHAR2(50),
  CreatorUsername VARCHAR2(50) REFERENCES UserAccount(Username)
);

CREATE TABLE TopicTag (
  TopicName VARCHAR2(50) NOT NULL REFERENCES Topic(Name),
  InterestId NUMBER(38) NOT NULL REFERENCES Interest(Id),
  PRIMARY KEY (TopicName, InterestId)
);

CREATE TABLE UserInterest (
  Username VARCHAR2(50) NOT NULL REFERENCES UserAccount(Username),
  InterestId NUMBER(38) NOT NULL REFERENCES Interest(Id),
  PRIMARY KEY (Username, InterestId)
);

CREATE TABLE Vote (
  Id NUMBER(38) NOT NULL PRIMARY KEY,
  Type VARCHAR2(100),
  TopicName VARCHAR2(100) REFERENCES Topic(Name),
  VoterUsername VARCHAR2(100) REFERENCES UserAccount(Username)
);

CREATE TABLE EditRequest (
  Num NUMBER(38) NOT NULL UNIQUE,
  TopicName VARCHAR2(50) NOT NULL UNIQUE REFERENCES Topic(Name),
  MergedBy VARCHAR2(50) NOT NULL REFERENCES UserAccount(Username),
  OpenedBy VARCHAR2(50) NOT NULL REFERENCES UserAccount(Username),
  MergeCommitId NUMBER(38) NOT NULL,
  PRIMARY KEY (Num, TopicName)
);

CREATE TABLE TopicChange (
  Id NUMBER(38) NOT NULL PRIMARY KEY,
  Time TIMESTAMP NOT NULL,
  EditRequestNumber NUMBER(38) NOT NULL REFERENCES EditRequest(Num),
  AuthorUsername VARCHAR2(50) REFERENCES UserAccount(Username),
  TopicName VARCHAR2(50) NOT NULL REFERENCES EditRequest(TopicName)
);

ALTER TABLE
  EditRequest
ADD
  FOREIGN KEY (MergeCommitId) REFERENCES TopicChange(Id);

CREATE SEQUENCE permission_seq INCREMENT BY 1 START WITH 0 MINVALUE 0 MAXVALUE 500;

CREATE SEQUENCE interest_seq INCREMENT BY 1 START WITH 0 MINVALUE 0 MAXVALUE 500;

CREATE SEQUENCE vote_seq INCREMENT BY 1 START WITH 0 MINVALUE 0 MAXVALUE 500;